FROM ubuntu:oracular

ARG GO_VERSION=latest
ENV GO_VERSION=${GO_VERSION}

RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y cmake
RUN apt-get install -y ethtool
RUN apt-get install -y gcc
RUN apt-get install -y g++
RUN apt-get install -y lrzsz
RUN apt-get install -y tcpdump
RUN apt-get install -y netcat-openbsd
RUN apt-get install -y net-tools
RUN apt-get install -y netsniff-ng
RUN apt-get install -y wget
RUN apt-get install -y which
RUN apt-get install -y faketime
RUN apt-get install -y vim
RUN apt-get install -y curl
RUN apt-get install -y file
RUN apt-get install -y tree
RUN apt-get install -y sshpass
RUN apt-get install -y zsh
RUN echo y | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"


RUN apt-get install locales
RUN locale-gen en_US.UTF-8
RUN update-locale LANG=en_US.UTF-8

RUN apt-get install -y tzdata

# 设置时区为Asia/Shanghai
ENV TZ=Asia/Shanghai

# 重新配置时区数据
RUN ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

# Add installation scripts
ADD ./install-golang.sh /usr/local/bin
ADD ./install-latest-golang.sh /usr/local/bin

# Make scripts executable
RUN chmod +x /usr/local/bin/install-golang.sh && \
    chmod +x /usr/local/bin/install-latest-golang.sh

RUN rm /usr/bin/sh && ln -s /usr/bin/bash /usr/bin/sh

# Install Go based on GO_VERSION
RUN if [ "$GO_VERSION" = "latest" ]; then \
        echo "GO_VERSION=latest, using install-latest-golang.sh" && \
        /usr/local/bin/install-latest-golang.sh; \
    else \
        echo "GO_VERSION=$GO_VERSION, using install-golang.sh" && \
        /usr/local/bin/install-golang.sh; \
    fi

ADD ./test_init.sh /usr/local/bin
CMD ["/usr/local/bin/test_init.sh"]
